sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /kinect2/qhd/points
   max_range: 2.0
   padding_offset: 0
   padding_scale: 1.0
   frame_subsample: 1
   point_subsample: 1
