stomp/arm_right:
  group_name: arm_right
  optimization:
    num_timesteps: 50
    num_iterations: 100
    num_iterations_after_valid: 0    
    num_rollouts: 10
    max_rollouts: 100
    initialization_method: 1 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.0
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.1, 1.0, 1.0, 0.4, 0.3, 0.3, 0.3]
    cost_functions:
       - class: stomp_moveit/CollisionCheck
         collision_penalty: 1.0
         cost_weight: 1.0
         kernel_window_percentage: 0.2
         longest_valid_joint_move: 0.05
#     - class: stomp_moveit/ObstacleDistanceGradient
#       max_distance: 0.2
#       cost_weight: 1.0
#       longest_valid_joint_move: 0.05 
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.002
        rgb: [0, 255, 0]
        marker_array_topic: trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/PolynomialSmoother
        poly_order: 5
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.01
        rgb: [0, 0, 150]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: trajectory
        marker_namespace: optimized
stomp/arm_left:
  group_name: arm_left
  optimization:
    num_timesteps: 40
    num_iterations: 40
    num_iterations_after_valid: 0    
    num_rollouts: 10
    max_rollouts: 10 
    initialization_method: 3 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.0
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.05, 0.4, 1.2, 0.4, 0.4, 0.1, 0.1]
    cost_functions:
      - class: stomp_moveit/CollisionCheck
        collision_penalty: 1.0
        cost_weight: 1.0
        kernel_window_percentage: 0.2
        longest_valid_joint_move: 0.05 
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [255, 255, 0]
        marker_array_topic: trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/UpdateLogger
        package: stomp_moveit
        directory: log
        filename: noisy_update.txt
      - class: stomp_moveit/ControlCostProjectionMatrix
      - class: stomp_moveit/UpdateLogger
        package: stomp_moveit
        directory: log
        filename: smoothed_update.txt
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.05
        rgb: [0, 191, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: trajectory
        marker_namespace: optimized
stomp/arms:
  group_name: arms
  optimization:
    num_timesteps: 40
    num_iterations: 40
    num_iterations_after_valid: 0    
    num_rollouts: 10
    max_rollouts: 10 
    initialization_method: 3 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.0
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.05, 0.4, 1.2, 0.4, 0.4, 0.1, 0.1, 0.05, 0.4, 1.2, 0.4, 0.4, 0.1, 0.1]
    cost_functions:
      - class: stomp_moveit/CollisionCheck 
        kernel_window_percentage: 0.2
        collision_penalty: 1.0
        cost_weight: 1.0
        longest_valid_joint_move: 0.05 
#      - class: stomp_moveit/ObstacleDistanceGradient
#        max_distance: 0.2
#        cost_weight: 1.0
#        longest_valid_joint_move: 0.05 
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.04
        rgb: [255, 255, 0]
        marker_array_topic: trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/PolynomialSmoother
        poly_order: 5
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.02
        rgb: [0, 191, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: trajectory
        marker_namespace: optimized    
stomp/sda5f:
  group_name: sda5f
  optimization:
    num_timesteps: 40
    num_iterations: 40
    num_iterations_after_valid: 0    
    num_rollouts: 10
    max_rollouts: 10 
    initialization_method: 3 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.0
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.05, 0.4, 1.2, 0.4, 0.4, 0.1, 0.1, 0.05, 0.4, 1.2, 0.4, 0.4, 0.1, 0.1, 0.05, 0.05]
    cost_functions:
      - class: stomp_moveit/CollisionCheck 
        kernel_window_percentage: 0.2
        collision_penalty: 1.0
        cost_weight: 1.0
        longest_valid_joint_move: 0.05 
#      - class: stomp_moveit/ObstacleDistanceGradient
#        max_distance: 0.2
#        cost_weight: 1.0
#        longest_valid_joint_move: 0.05 
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.04
        rgb: [255, 255, 0]
        marker_array_topic: trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/PolynomialSmoother
        poly_order: 5
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.02
        rgb: [0, 191, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: trajectory
        marker_namespace: optimized   
